
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=taskdb
      - DB_USER=taskuser
      - DB_PASS=taskpass
      - DB_HOST=db
      - DB_PORT=5432
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: